# Generated by Django 5.2.15 on 2026-06-17 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_specialoffer'),
        ('medical_catalog', '0002_package_packageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
            },
        ),
        migrations.CreateModel(
            name='PricingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('procedure_name', models.CharField(max_length=500)),
                ('requested_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('service_done', 'Service Done'), ('unknown', 'Unknown')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_requests', to='contracts.contractentity')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_requests', to='pricing_requests.patient')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_requests', to='medical_catalog.specialty')),
                ('sub_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_requests', to='contracts.subcompany')),
            ],
            options={
                'verbose_name': 'طلب تسعير',
                'verbose_name_plural': 'طلبات التسعير',
            },
        ),
    ]
