# Generated by Django 5.2.15 on 2026-06-17 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('report', 'Report'), ('approval', 'Approval'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='pricing_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pricing_requests.pricingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PricingRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('accounts', 'Accounts'), ('or', 'OR Coordinator'), ('approvals', 'Approvals')], max_length=20)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pricing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pricing_requests.pricingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PricingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pricing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pricing_requests.pricingrequest')),
            ],
        ),
    ]
