# Generated by Django 5.2.15 on 2026-06-17 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_professionalfeerule_classification_and_more'),
        ('medical_catalog', '0003_alter_package_code_alter_packageattachment_package_and_more'),
        ('pricing_requests', '0002_pricingrequestfile_pricingrequestnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrequest',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='approval_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='approval_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pricingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('service_done', 'Service Done'), ('patient_refused', 'Patient Refused'), ('unknown', 'Unknown')], default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='pricingrequest',
            index=models.Index(fields=['status'], name='pricing_req_status_8572c7_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrequest',
            index=models.Index(fields=['entity'], name='pricing_req_entity__1a5438_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrequest',
            index=models.Index(fields=['specialty'], name='pricing_req_special_079085_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrequest',
            index=models.Index(fields=['expected_admission_date'], name='pricing_req_expecte_c61aa8_idx'),
        ),
    ]
