# Generated by Django 5.2.15 on 2026-06-18 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0003_pricingrequest_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingstatushistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='agent_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent1_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='agent_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent2_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='billing_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='main_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pricing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricingrequestnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_request_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricingrequestnote',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('accounts', 'Accounts'), ('or_coordinator', 'OR Coordinator'), ('approvals', 'Approvals')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pricingstatushistory',
            index=models.Index(fields=['pricing_request'], name='pricing_req_pricing_2fe16a_idx'),
        ),
    ]
