# Generated by Django 5.2.15 on 2026-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0004_alter_pricingstatushistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrequestnote',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
