# Generated by Django 5.2.15 on 2026-07-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0005_pricingrequestnote_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=100, verbose_name='الرقم الحسابى')),
                ('patient_type', models.CharField(db_index=True, max_length=50, verbose_name='نوع المريض')),
                ('patient_name', models.CharField(max_length=255, verbose_name='اسم المريض')),
                ('admission_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الدخول')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('stay_duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة الإقامة')),
                ('department_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم القسم')),
                ('service_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم الخدمة')),
                ('service_code', models.CharField(db_index=True, max_length=100, verbose_name='الكود')),
                ('service_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='التاريخ')),
                ('insurance_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='شركة التأمين')),
                ('sub_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشركة الفرعية')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سجل خدمة',
                'verbose_name_plural': 'سجلات الخدمات',
                'ordering': ['-service_date', 'service_name'],
                'indexes': [models.Index(fields=['service_name'], name='pricing_req_service_209684_idx'), models.Index(fields=['service_code'], name='pricing_req_service_553859_idx'), models.Index(fields=['department_name'], name='pricing_req_departm_46af8b_idx'), models.Index(fields=['patient_type'], name='pricing_req_patient_f5279e_idx'), models.Index(fields=['service_date'], name='pricing_req_service_ea4b8c_idx'), models.Index(fields=['insurance_company'], name='pricing_req_insuran_fa2372_idx')],
            },
        ),
    ]
