# Generated by Django 5.2.15 on 2026-07-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0006_servicerecord'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicerecord',
            constraint=models.UniqueConstraint(fields=('account_number', 'service_code'), name='unique_service_record'),
        ),
    ]
