# Generated by Django 5.2.15 on 2026-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0007_servicerecord_unique_service_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ التسعير')),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الجروب')),
                ('patient_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المريض')),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الشركة')),
                ('doctor_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم الطبيب')),
                ('report_name', models.TextField(blank=True, null=True, verbose_name='التقرير')),
                ('procedure_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الإجراء')),
                ('specialty_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='التخصص')),
                ('pricing_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع التسعير')),
                ('card_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='رقم الكارنية')),
                ('accountant_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم المحاسب')),
                ('cost_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات خاصة بالتكلفة')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تفصيل تسعير',
                'verbose_name_plural': 'تفاصيل التسعير',
                'ordering': ['-pricing_date', '-id'],
                'indexes': [models.Index(fields=['patient_name'], name='pricing_req_patient_6d7597_idx'), models.Index(fields=['company_name'], name='pricing_req_company_5ed970_idx'), models.Index(fields=['doctor_name'], name='pricing_req_doctor__35f119_idx'), models.Index(fields=['specialty_name'], name='pricing_req_special_31fc77_idx'), models.Index(fields=['group_name'], name='pricing_req_group_n_2beb63_idx'), models.Index(fields=['pricing_date'], name='pricing_req_pricing_4841c4_idx')],
            },
        ),
    ]
