# Generated by Django 5.2.15 on 2026-07-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0008_pricingdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingdetail',
            options={'ordering': ['-pricing_date', '-cost'], 'verbose_name': 'تفصيل تسعير', 'verbose_name_plural': 'تفاصيل التسعير'},
        ),
        migrations.CreateModel(
            name='SimilarInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=100, verbose_name='الرقم الحسابي')),
                ('medical_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الرقم الطبي')),
                ('patient_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المريض')),
                ('admission_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الدخول')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('stay_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدة الاقامة')),
                ('specialty_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='التخصص')),
                ('doctor_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم الطبيب')),
                ('operation_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم العملية')),
                ('entity_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الجهة')),
                ('sub_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشركة الفرعية')),
                ('building', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدور / المبنى')),
                ('total_invoice', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_invoice', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company_share', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('patient_share', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice_status', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='حالة الفاتورة')),
                ('invoice_closed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الفاتورة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فاتورة مماثلة',
                'verbose_name_plural': 'فواتير مماثلة',
                'ordering': ['-admission_date', '-id'],
                'indexes': [models.Index(fields=['patient_name'], name='pricing_req_patient_b0240e_idx'), models.Index(fields=['operation_name'], name='pricing_req_operati_a3ebe0_idx'), models.Index(fields=['entity_name'], name='pricing_req_entity__6a8d42_idx'), models.Index(fields=['doctor_name'], name='pricing_req_doctor__76ff05_idx'), models.Index(fields=['specialty_name'], name='pricing_req_special_d4fe99_idx'), models.Index(fields=['admission_date'], name='pricing_req_admissi_2ab9f8_idx')],
            },
        ),
    ]
