# Generated by Django 5.2.15 on 2026-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0009_alter_pricingdetail_options_similarinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='الكود')),
                ('operation_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم العملية')),
                ('specialty_name', models.CharField(db_index=True, max_length=255, verbose_name='التخصص')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='التصنيف')),
                ('english_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='المسمى باللغة الإنجليزية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'توصيف عملية',
                'verbose_name_plural': 'توصيف العمليات',
                'ordering': ['operation_name'],
                'indexes': [models.Index(fields=['operation_name'], name='pricing_req_operati_647102_idx'), models.Index(fields=['specialty_name'], name='pricing_req_special_eb3f88_idx')],
            },
        ),
    ]
