# Generated by Django 5.2.15 on 2026-07-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0010_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(db_index=True, max_length=255, verbose_name='الجهة')),
                ('financial_category', models.CharField(db_index=True, max_length=100, verbose_name='الفئة المالية')),
                ('price_list', models.CharField(blank=True, max_length=100, null=True, verbose_name='قائمة الأسعار')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='التصنيف')),
                ('surgeon_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anesthesia_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assistant_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'أتعاب عملية',
                'verbose_name_plural': 'احتساب أتعاب العمليات',
                'ordering': ['entity_name', 'category'],
                'indexes': [models.Index(fields=['entity_name'], name='pricing_req_entity__4763fc_idx'), models.Index(fields=['financial_category'], name='pricing_req_financi_71ba07_idx'), models.Index(fields=['category'], name='pricing_req_categor_32f9ee_idx')],
            },
        ),
    ]
