# Generated by Django 5.2.15 on 2026-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0011_procedurefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurefee',
            name='discount_rate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='معدل الخصم'),
        ),
    ]
