# Generated by Django 5.2.15 on 2026-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0012_alter_procedurefee_discount_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDiscountRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('financial_category', models.CharField(max_length=100)),
                ('price_list', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_discount', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('external_discount', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-internal_discount', '-external_discount', 'company_name'],
            },
        ),
    ]
