# Generated by Django 5.2.15 on 2026-07-09 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0014_companyexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('داخلي', 'داخلي'), ('خارجي', 'خارجي')], max_length=20)),
                ('service_name', models.CharField(max_length=255)),
                ('discount_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('net_price', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyExceptionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(db_index=True, max_length=255)),
                ('financial_category', models.CharField(blank=True, max_length=100, null=True)),
                ('price_list', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Exception',
                'verbose_name_plural': 'Company Exceptions',
                'ordering': ['entity_name'],
            },
        ),
        migrations.DeleteModel(
            name='CompanyDiscountRank',
        ),
        migrations.DeleteModel(
            name='CompanyException',
        ),
        migrations.AddField(
            model_name='companyexceptionitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing_requests.companyexceptionprofile'),
        ),
    ]
