# Generated by Django 5.2.15 on 2026-07-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0015_companyexceptionitem_companyexceptionprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDiscountRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('financial_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفئة المالية')),
                ('section', models.CharField(choices=[('داخلي', 'داخلي'), ('خارجي', 'خارجي')], max_length=20, verbose_name='القسم')),
                ('service_name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نسبة الخصم')),
                ('rank', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ترتيب خصم شركة',
                'verbose_name_plural': 'ترتيب خصومات الشركات',
                'ordering': ['rank'],
            },
        ),
    ]
