# Generated by Django 5.2.15 on 2026-07-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0016_companydiscountrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(db_index=True, max_length=255)),
                ('financial_category', models.CharField(blank=True, max_length=100, null=True)),
                ('price_list', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_discount', models.DecimalField(decimal_places=2, default=0, help_text='معدل الخصم الداخلي', max_digits=6)),
                ('internal_details', models.TextField(blank=True, help_text='تفاصيل الخصم الداخلي', null=True)),
                ('external_discount', models.DecimalField(decimal_places=2, default=0, help_text='معدل الخصم الخارجي', max_digits=6)),
                ('external_details', models.TextField(blank=True, help_text='تفاصيل الخصم الخارجي', null=True)),
                ('attachment', models.TextField(blank=True, help_text='رابط المرفقات', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'استثناءات الشركة',
                'verbose_name_plural': 'استثناءات الشركات',
                'ordering': ['entity_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='companydiscountrank',
            options={'ordering': ['-internal_discount', '-external_discount', 'company_name']},
        ),
        migrations.RemoveField(
            model_name='companydiscountrank',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='companydiscountrank',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='companydiscountrank',
            name='section',
        ),
        migrations.RemoveField(
            model_name='companydiscountrank',
            name='service_name',
        ),
        migrations.AddField(
            model_name='companydiscountrank',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydiscountrank',
            name='external_discount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='companydiscountrank',
            name='internal_discount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='companydiscountrank',
            name='price_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydiscountrank',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companydiscountrank',
            name='financial_category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyExceptionItem',
        ),
        migrations.DeleteModel(
            name='CompanyExceptionProfile',
        ),
    ]
