# Generated by Django 5.2.15 on 2026-07-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0017_companyexception_alter_companydiscountrank_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExceptionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم الجهة')),
                ('financial_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفئة المالية')),
                ('price_list', models.CharField(blank=True, max_length=100, null=True, verbose_name='قائمة الأسعار')),
                ('attachment', models.TextField(blank=True, null=True, verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف استثناءات شركة',
                'verbose_name_plural': 'ملفات استثناءات الشركات',
                'ordering': ['entity_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyExceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('داخلي', 'داخلي'), ('خارجي', 'خارجي')], max_length=20, verbose_name='القسم')),
                ('service_name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('discount_rate', models.CharField(blank=True, max_length=50, null=True, verbose_name='نسبة الخصم')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('net_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='السعر الصافي')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing_requests.companyexceptionprofile', verbose_name='ملف الاستثناءات')),
            ],
            options={
                'verbose_name': 'عنصر استثناء',
                'verbose_name_plural': 'عناصر الاستثناءات',
                'ordering': ['section', 'display_order'],
            },
        ),
    ]
