# Generated by Django 5.2.15 on 2026-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0018_companyexceptionprofile_companyexceptionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الرقم الطبي')),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الرقم الحسابى')),
                ('patient_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المريض')),
                ('admission_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الدخول')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('month', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='الشهر')),
                ('specialty', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='التخصص')),
                ('package_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم الباكدج')),
                ('entity_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الجهه')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='القطاع')),
                ('payment_type', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='نوع الدفع')),
                ('sub_company', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الشركه الفرعيه')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقرير وإحصائية',
                'verbose_name_plural': 'التقارير والإحصائيات',
                'ordering': ['-admission_date', '-id'],
                'indexes': [models.Index(fields=['patient_name'], name='pricing_req_patient_c5f000_idx'), models.Index(fields=['entity_name'], name='pricing_req_entity__356b5a_idx'), models.Index(fields=['specialty'], name='pricing_req_special_d4dfb2_idx'), models.Index(fields=['package_name'], name='pricing_req_package_a1c05c_idx'), models.Index(fields=['admission_date'], name='pricing_req_admissi_bd4687_idx'), models.Index(fields=['sector'], name='pricing_req_sector_5efd5a_idx'), models.Index(fields=['account_number'], name='pricing_req_account_ce32b1_idx'), models.Index(fields=['month'], name='pricing_req_month_e1d649_idx'), models.Index(fields=['payment_type'], name='pricing_req_payment_925c48_idx')],
            },
        ),
    ]
