# Generated by Django 5.2.15 on 2026-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0019_reportstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملحق او رئيسى')),
                ('patient_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المريض')),
                ('card_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='رقم الكارنية')),
                ('company', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الشركة')),
                ('sub_account', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Sub Account')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='التاريخ')),
                ('medical_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الرقم الطبي')),
                ('doctor_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الطبيب')),
                ('specialty', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='التخصص')),
                ('required', models.TextField(blank=True, null=True, verbose_name='المطلوب')),
                ('procedure', models.TextField(blank=True, null=True, verbose_name='الاجراء')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التليفون')),
                ('agent_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent 1')),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Status')),
                ('main_status', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Main Status')),
                ('initial_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفه المبدئية')),
                ('pricing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسعير')),
                ('pricing_responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول التسعير')),
                ('billing_status', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Billing Status')),
                ('approval_review_responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول مراجعة الموافقة و التسعير')),
                ('accounts_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحسابات')),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الرقم الحسابى')),
                ('received_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة المستلمه')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Report')),
                ('approval', models.CharField(blank=True, max_length=255, null=True, verbose_name='Approval')),
                ('request_approval_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Request and Approval NO.')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('last_update', models.DateField(blank=True, null=True, verbose_name='Last Update')),
                ('agent_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent 2')),
                ('opd_sales_cs', models.CharField(blank=True, max_length=100, null=True, verbose_name='OPD ,Sales or CS')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول')),
                ('or_coordinator_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الـ OR Coordinator')),
                ('sales_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='sales account')),
                ('head', models.CharField(blank=True, max_length=100, null=True, verbose_name='Head')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='USER')),
                ('sales_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات السيلز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'متابعة موافقة خارجي',
                'verbose_name_plural': 'متابعة موافقات الخارجي',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['patient_name'], name='pricing_req_patient_a7e6dc_idx'), models.Index(fields=['company'], name='pricing_req_company_632c32_idx'), models.Index(fields=['specialty'], name='pricing_req_special_abb876_idx'), models.Index(fields=['status'], name='pricing_req_status_15e5cc_idx'), models.Index(fields=['main_status'], name='pricing_req_main_st_52904b_idx'), models.Index(fields=['date'], name='pricing_req_date_687039_idx'), models.Index(fields=['account_number'], name='pricing_req_account_e0cdf1_idx')],
            },
        ),
    ]
