# Generated by Django 5.2.15 on 2026-07-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0020_externalapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapproval',
            name='patient_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم المريض'),
        ),
    ]
