# Generated by Django 5.2.15 on 2026-07-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0021_alter_externalapproval_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ'),
        ),
    ]
