# Generated by Django 5.2.15 on 2026-07-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0022_alter_servicerecord_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='total_invoice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='اجمالي الفاتورة'),
        ),
    ]
