# Generated by Django 5.2.15 on 2026-07-22 12:33

import pricing_requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0023_servicerecord_total_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurefee',
            name='category',
            field=models.CharField(db_index=True, max_length=100, validators=[pricing_requests.models.validate_category], verbose_name='التصنيف'),
        ),
    ]
