# Generated by Django 5.2.15 on 2026-07-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0024_alter_procedurefee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatistic',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الكود'),
        ),
        migrations.AddField(
            model_name='reportstatistic',
            name='doctor_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم الطبيب'),
        ),
        migrations.AddField(
            model_name='reportstatistic',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='قيمة الفاتوره'),
        ),
        migrations.AddField(
            model_name='reportstatistic',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='reportstatistic',
            name='patient_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المريض'),
        ),
        migrations.AddField(
            model_name='reportstatistic',
            name='stay_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة الاقامه'),
        ),
        migrations.AddIndex(
            model_name='reportstatistic',
            index=models.Index(fields=['doctor_name'], name='pricing_req_doctor__511d71_idx'),
        ),
    ]
