# Generated by Django 5.2.15 on 2026-08-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0025_reportstatistic_code_reportstatistic_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricingdetail',
            constraint=models.UniqueConstraint(fields=('patient_name', 'company_name', 'procedure_name', 'pricing_date'), name='unique_pricing_detail'),
        ),
    ]
