# Generated by Django 5.2.15 on 2026-08-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0026_pricingdetail_unique_pricing_detail'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companydiscountrank',
            constraint=models.UniqueConstraint(fields=('company_name',), name='unique_company_discount_rank'),
        ),
    ]
