# Generated by Django 5.2.15 on 2026-08-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0027_companydiscountrank_unique_company_discount_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الكود'),
        ),
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('code', 'category'), name='unique_procedure_code_category'),
        ),
    ]
