# Generated by Django 5.2.15 on 2026-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0028_alter_procedure_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdetail',
            name='procedure_name',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='الإجراء'),
        ),
    ]
