# Generated by Django 5.2.15 on 2026-08-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0029_alter_pricingdetail_procedure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydiscountrank',
            name='external_discount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='companydiscountrank',
            name='internal_discount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
