# Generated by Django 5.2.15 on 2026-08-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0030_alter_companydiscountrank_external_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingdetail',
            name='report_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط التقرير'),
        ),
    ]
