# Generated by Django 5.2.15 on 2026-08-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0031_pricingdetail_report_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapproval',
            name='received_cost',
            field=models.TextField(blank=True, null=True, verbose_name='التكلفة المستلمه'),
        ),
    ]
