# Generated by Django 5.2.15 on 2026-08-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0032_alter_externalapproval_received_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
