# Generated by Django 5.2.15 on 2026-08-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0033_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarinvoice',
            name='operation_description',
            field=models.TextField(blank=True, null=True, verbose_name='توصيف العملية'),
        ),
    ]
