# Generated by Django 5.2.15 on 2026-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0034_similarinvoice_operation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatistic',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم القسم'),
        ),
        migrations.AddField(
            model_name='reportstatistic',
            name='procedure_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الإجراء'),
        ),
        migrations.AddField(
            model_name='reportstatistic',
            name='service_name_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='اسم الخدمة عربي'),
        ),
    ]
