# Generated by Django 5.2.15 on 2026-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0035_reportstatistic_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarinvoice',
            name='admission_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة الدخول'),
        ),
        migrations.AddField(
            model_name='similarinvoice',
            name='admission_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الدخول'),
        ),
        migrations.AddField(
            model_name='similarinvoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='similarinvoice',
            name='operating_room_opened',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='فتح غرفة العمليات'),
        ),
        migrations.AddField(
            model_name='similarinvoice',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرفة'),
        ),
    ]
