# Generated by Django 5.2.15 on 2026-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0036_similarinvoice_admission_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicerecord',
            name='unique_service_record',
        ),
        migrations.AddConstraint(
            model_name='servicerecord',
            constraint=models.UniqueConstraint(fields=('account_number', 'service_code', 'service_date'), name='unique_service_record'),
        ),
    ]
