# Generated by Django 5.2.15 on 2026-09-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0037_remove_servicerecord_unique_service_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapproval',
            name='approval',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='externalapproval',
            name='notes',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='externalapproval',
            name='or_coordinator_notes',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='ملاحظات الـ OR Coordinator'),
        ),
        migrations.AlterField(
            model_name='externalapproval',
            name='procedure',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='الاجراء'),
        ),
    ]
