# Generated by Django 5.2.15 on 2026-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0038_alter_externalapproval_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapproval',
            name='main_status',
            field=models.CharField(blank=True, db_index=True, max_length=350, null=True, verbose_name='Main Status'),
        ),
        migrations.AlterField(
            model_name='externalapproval',
            name='request_approval_no',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Request and Approval NO.'),
        ),
        migrations.AlterField(
            model_name='pricingrequest',
            name='main_status',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
