# Generated by Django 5.2.15 on 2026-09-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0039_alter_externalapproval_main_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='department_name_search',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='اسم القسم للبحث'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='service_name_search',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='اسم الخدمة للبحث'),
        ),
    ]
