# Generated by Django 5.2.15 on 2026-09-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_requests', '0040_servicerecord_department_name_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='doctor_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='اسم الطبيب'),
        ),
    ]
