# Generated by Django 5.2.15 on 2026-06-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الجهة',
                'verbose_name_plural': 'الجهات المتعاقدة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قائمة أسعار',
                'verbose_name_plural': 'قوائم الأسعار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_categories', to='contracts.contractentity')),
            ],
            options={
                'verbose_name': 'الفئة المالية',
                'verbose_name_plural': 'الفئات المالية',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_service_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.contractentity')),
                ('financial_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.financialcategory')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.pricelist')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
            },
        ),
        migrations.CreateModel(
            name='SubCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_companies', to='contracts.contractentity')),
            ],
            options={
                'verbose_name': 'شركة فرعية',
                'verbose_name_plural': 'الشركات الفرعية',
                'ordering': ['name'],
            },
        ),
    ]
