# Generated by Django 5.2.15 on 2026-06-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('section', models.CharField(choices=[('internal', 'داخلي'), ('external', 'خارجي')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'فئة تغطية',
                'verbose_name_plural': 'فئات التغطية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exceptions', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_rules', to='contracts.coveragecategory')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'قاعدة خصم',
                'verbose_name_plural': 'قواعد الخصومات',
            },
        ),
    ]
