# Generated by Django 5.2.15 on 2026-06-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_coveragecategory_coveragerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=50)),
                ('surgeon_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anesthesia_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assistant_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_note', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_fee_rules', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'أتعاب الأطباء',
                'verbose_name_plural': 'أتعاب الأطباء',
            },
        ),
    ]
