# Generated by Django 5.2.15 on 2026-06-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_professionalfeerule'),
        ('medical_catalog', '0002_package_packageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(max_length=255)),
                ('procedure_name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='contracts.contractentity')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_offers', to='medical_catalog.specialty')),
            ],
            options={
                'verbose_name': 'عرض خاص',
                'verbose_name_plural': 'العروض الخاصة',
            },
        ),
    ]
