# Generated by Django 5.2.15 on 2026-06-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_specialoffer'),
        ('medical_catalog', '0003_alter_package_code_alter_packageattachment_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalfeerule',
            name='classification',
            field=models.CharField(choices=[('صغرى', 'صغرى'), ('متوسطة', 'متوسطة'), ('كبرى', 'كبرى'), ('مهارة', 'مهارة'), ('طابع خاص', 'طابع خاص'), ('متقدمة', 'متقدمة')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='coveragerule',
            index=models.Index(fields=['contract'], name='contracts_c_contrac_3b8822_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalfeerule',
            index=models.Index(fields=['contract'], name='contracts_p_contrac_32b3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['entity'], name='contracts_s_entity__fd9ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['specialty'], name='contracts_s_special_5005e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('entity', 'financial_category', 'price_list'), name='unique_contract_configuration'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.UniqueConstraint(fields=('contract', 'category'), name='unique_coverage_rule_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='unique_financial_category_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='professionalfeerule',
            constraint=models.UniqueConstraint(fields=('contract', 'classification'), name='unique_professional_fee_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='subcompany',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='unique_subcompany_per_entity'),
        ),
    ]
