# Generated by Django 5.2.15 on 2026-06-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_professionalfeerule_classification_and_more'),
        ('medical_catalog', '0003_alter_package_code_alter_packageattachment_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cash_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_packages', to='contracts.contract')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_packages', to='medical_catalog.package')),
            ],
            options={
                'verbose_name': 'تسعير الباكدج',
                'verbose_name_plural': 'تسعير الباكدجات',
                'indexes': [models.Index(fields=['contract'], name='contracts_c_contrac_50ab47_idx'), models.Index(fields=['package'], name='contracts_c_package_0791ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'package'), name='unique_package_per_contract')],
            },
        ),
    ]
