# Generated by Django 5.2.15 on 2026-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpackage',
            name='price_list_applied',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractpackage',
            name='special_offer_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
