# Generated by Django 5.2.15 on 2026-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractpackage_price_list_applied_and_more'),
        ('medical_catalog', '0005_package_cash_price_package_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpackage',
            name='cash_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر النقدي'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='current_discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم الحالية'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='ساري من'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='package_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الباكدج'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='price_list_applied',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قائمة الأسعار المطبقة'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='special_offer_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شركة العرض الخاص'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='special_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر العرض الخاص'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='total_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الإجمالي قبل الخصم'),
        ),
        migrations.AlterField(
            model_name='contractpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddIndex(
            model_name='contractpackage',
            index=models.Index(fields=['contract', 'package'], name='contracts_c_contrac_615b56_idx'),
        ),
    ]
