# Generated by Django 5.2.15 on 2026-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contractpackage_cash_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpackage',
            name='approval_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractpackage',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
