# Generated by Django 5.2.15 on 2026-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contractpackage_approval_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpackage',
            name='suggested_discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contractpackage',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
