# Generated by Django 5.2.15 on 2026-06-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contractpackage_suggested_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpackage',
            name='current_discount_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الخصم الحالي'),
        ),
    ]
