# Generated by Django 5.2.15 on 2026-07-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contractpackage_current_discount_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='medical_service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الخدمة الطبية'),
        ),
        migrations.AddField(
            model_name='contract',
            name='operating_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='تعليمات التشغيل'),
        ),
    ]
