# Generated by Django 5.2.15 on 2026-07-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contract_medical_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='contracts.contract')),
            ],
        ),
    ]
