# Generated by Django 5.2.15 on 2026-07-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_companydiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='operating_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
