# Generated by Django 5.2.15 on 2026-07-02 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contract_operating_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDiscountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('financial_category', models.CharField(blank=True, max_length=100)),
                ('price_list', models.CharField(blank=True, max_length=100)),
                ('operating_pdf', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companydiscount',
            name='contract',
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='discount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='item_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='section',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydiscount',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='contracts.companydiscountprofile'),
        ),
    ]
