# Generated by Django 5.2.15 on 2026-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_companydiscountprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
