# Generated by Django 5.2.15 on 2026-08-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_specialoffer_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydiscount',
            options={'verbose_name': 'Company Discount', 'verbose_name_plural': 'Company Discounts'},
        ),
        migrations.AlterModelOptions(
            name='companydiscountprofile',
            options={'verbose_name': 'Company Discount Profile', 'verbose_name_plural': 'Company Discount Profiles'},
        ),
        migrations.AddIndex(
            model_name='companydiscount',
            index=models.Index(fields=['profile', 'section'], name='contracts_c_profile_8f82d1_idx'),
        ),
        migrations.AddIndex(
            model_name='companydiscountprofile',
            index=models.Index(fields=['company_name', 'financial_category'], name='contracts_c_company_820cbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='companydiscount',
            constraint=models.UniqueConstraint(fields=('profile', 'section', 'item_name'), name='unique_company_discount'),
        ),
        migrations.AddConstraint(
            model_name='companydiscountprofile',
            constraint=models.UniqueConstraint(fields=('company_name', 'financial_category'), name='unique_company_discount_profile'),
        ),
    ]
