# Generated by Django 5.2.15 on 2026-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_companydiscount_options_and_more'),
        ('medical_catalog', '0008_package_unique_package_per_entity_code_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specialoffer',
            constraint=models.UniqueConstraint(fields=('entity', 'offer_for', 'specialty', 'procedure_name'), name='unique_special_offer'),
        ),
    ]
