# Generated by Django 5.2.15 on 2026-07-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, max_length=200)),
                ('logs', models.TextField(blank=True)),
                ('duration', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
