# Generated by Django 5.2.15 on 2026-08-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_phone_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('packages_cash_full', 'صلاحية كاملة على الباكدجات النقدية'), ('packages_credit_basic', 'استعراض البيانات الأساسية للباكدجات الآجلة'), ('packages_credit_full', 'صلاحية كاملة على الباكدجات الآجلة'), ('patients_search', 'البحث عن المرضى'), ('patients_view', 'استعراض بيانات المرضى'), ('approvals_view', 'استعراض ومتابعة الموافقات الخارجية'), ('approvals_statistics', 'استعراض إحصائيات الموافقات'), ('approvals_edit', 'تعديل بيانات الموافقات'), ('doctors_view_all', 'استعراض جميع الأطباء'), ('doctors_view_own', 'استعراض حالات الطبيب الخاصة به'), ('doctors_edit', 'تعديل بيانات الأطباء'), ('financial_full', 'صلاحية كاملة على البيانات المالية والتعاقدية'), ('system_manage', 'إدارة النظام'), ('users_manage', 'إدارة المستخدمين'), ('roles_manage', 'إدارة الأدوار والصلاحيات')], 'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission', verbose_name='الصلاحيات'),
        ),
    ]
