# Generated by Django 5.2.15 on 2026-08-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الطبيب المرتبط بالحساب'),
        ),
    ]
