# Generated by Django 5.2.15 on 2026-08-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_doctors',
            field=models.JSONField(blank=True, default=list, verbose_name='الأطباء الإضافيين المسموح بمتابعتهم'),
        ),
    ]
