# Generated by Django 5.2.15 on 2026-06-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم التخصص')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'التخصص',
                'verbose_name_plural': 'التخصصات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=500)),
                ('name_en', models.CharField(blank=True, max_length=500, null=True)),
                ('classification', models.CharField(blank=True, choices=[('صغرى', 'صغرى'), ('متوسطة', 'متوسطة'), ('كبرى', 'كبرى'), ('مهارة', 'مهارة'), ('طابع خاص', 'طابع خاص'), ('متقدمة', 'متقدمة')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='medical_catalog.specialty')),
            ],
            options={
                'verbose_name': 'الإجراء',
                'verbose_name_plural': 'الإجراءات',
                'ordering': ['code'],
            },
        ),
    ]
