# Generated by Django 5.2.15 on 2026-06-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('stay_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_cash_package', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='medical_catalog.procedure')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='medical_catalog.specialty')),
            ],
            options={
                'verbose_name': 'الباكدج',
                'verbose_name_plural': 'الباكدجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_pdf', models.FileField(blank=True, null=True, upload_to='packages/includes/')),
                ('operation_instruction_pdf', models.FileField(blank=True, null=True, upload_to='packages/instructions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_catalog.package')),
            ],
            options={
                'verbose_name': 'مرفق الباكدج',
                'verbose_name_plural': 'مرفقات الباكدجات',
            },
        ),
    ]
