# Generated by Django 5.2.15 on 2026-06-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_catalog', '0002_package_packageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='packageattachment',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='medical_catalog.package'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['specialty'], name='medical_cat_special_1986b9_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['specialty'], name='medical_cat_special_0542a6_idx'),
        ),
    ]
