# Generated by Django 5.2.15 on 2026-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_catalog', '0003_alter_package_code_alter_packageattachment_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
