# Generated by Django 5.2.15 on 2026-06-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractpackage_price_list_applied_and_more'),
        ('medical_catalog', '0004_package_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cash_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر النقدي'),
        ),
        migrations.AddField(
            model_name='package',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العقد'),
        ),
        migrations.AddField(
            model_name='package',
            name='current_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الخصم الحالي'),
        ),
        migrations.AddField(
            model_name='package',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='contracts.contractentity', verbose_name='الجهة المتعاقدة'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_list_applied',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قائمة الأسعار المطبقة'),
        ),
        migrations.AddField(
            model_name='package',
            name='special_offer_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شركة العرض الخاص'),
        ),
        migrations.AddField(
            model_name='package',
            name='special_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر العرض الخاص'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر الإجمالي'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_without_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الإجمالي قبل الخصم'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['entity'], name='medical_cat_entity__a83a5b_idx'),
        ),
    ]
