# Generated by Django 5.2.15 on 2026-06-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_catalog', '0005_package_cash_price_package_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
