# Generated by Django 5.2.15 on 2026-08-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_specialoffer_price'),
        ('medical_catalog', '0006_package_package_note'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['code', 'entity'], name='medical_cat_code_7a8572_idx'),
        ),
    ]
