# Generated by Django 5.2.15 on 2026-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_specialoffer_price'),
        ('medical_catalog', '0007_package_medical_cat_code_7a8572_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('entity', 'code', 'name'), name='unique_package_per_entity_code_name'),
        ),
    ]
