# Generated by Django 5.2.15 on 2026-08-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_catalog', '0008_package_unique_package_per_entity_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('code', 'classification'), name='unique_procedure_code_classification'),
        ),
    ]
