# Generated by Django 5.2.15 on 2026-08-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_catalog', '0009_alter_procedure_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageattachment',
            name='operation_instruction_drive_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Drive File ID - تعليمات التشغيل'),
        ),
        migrations.AddField(
            model_name='packageattachment',
            name='operation_instruction_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='اسم ملف تعليمات التشغيل'),
        ),
        migrations.AddField(
            model_name='packageattachment',
            name='operation_instruction_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط تعليمات التشغيل'),
        ),
        migrations.AddField(
            model_name='packageattachment',
            name='package_pdf_drive_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Drive File ID - مشتملات'),
        ),
        migrations.AddField(
            model_name='packageattachment',
            name='package_pdf_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='اسم ملف مشتملات الباكدج'),
        ),
        migrations.AddField(
            model_name='packageattachment',
            name='package_pdf_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط مشتملات الباكدج'),
        ),
    ]
