# project/settings.py

"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mbdn9)+91#j^)w^jk4skrz_h_2nx_j&6l)!-=fdj*2sogl^m=h'

# ✅ SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # ⚠️ خليها False في production

ALLOWED_HOSTS = [
    # "mih-automated-pricing.up.railway.app",
    "web-production-8d018.up.railway.app",
    "127.0.0.1",
    "localhost",
    ".railway.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    # "https://mih-automated-pricing.up.railway.app",
    "https://web-production-8d018.up.railway.app",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    'django.contrib.humanize',
    
    # Apps
    'accounts',
    'medical_catalog',
    'contracts',
    'pricing_requests',
    'api',
    'imports',
    'pricing_engine',
    'dashboard',
    'frontend',
]

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# # Database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'railway',
#         'USER': 'postgres',
#         'PASSWORD': 'CJNFXTSwAvrlDwSdwqypPizihWhLRdDM',
#         'HOST': 'tokaido.proxy.rlwy.net',
#         'PORT': '16688',
#         'OPTIONS': {
#             'sslmode': 'require',
#             'connect_timeout': 60,
#             'keepalives': 1,
#             'keepalives_idle': 30,
#             'keepalives_interval': 10,
#             'keepalives_count': 5,
#         },
#         'CONN_MAX_AGE': 60,
#         'CONN_HEALTH_CHECKS': True,
#     }
# }


# # ✅ ==========================================================
# # ✅ إعدادات منع Internal Server Error
# # ✅ ==========================================================

# # ✅ زيادة حجم البيانات المسموح بها
# DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 100  # 100 MB
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# # ✅ زيادة مهلة الطلبات (لعمليات التحديث الطويلة)
# # ✅ ملحوظة: في Railway، المهلة الافتراضية 60 ثانية
# # ✅ الحل الأفضل هو تشغيل التحديث في الخلفية (Background Task)

# # ✅ إعدادات Logging
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
#         },
#     },
#     'root': {
#         'handlers': ['console', 'file'],
#         'level': 'INFO',
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console', 'file'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'ERROR',
#         },
#     },
# }



# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'fsbiCuHDERshMImzTkGfKjSwVZWaWZor',
        'HOST': 'shortline.proxy.rlwy.net',
        'PORT': '40857',
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': 60,
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        },
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }
}


# ✅ ==========================================================
# ✅ إعدادات منع Internal Server Error
# ✅ ==========================================================

# ✅ زيادة حجم البيانات المسموح بها
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 100  # 100 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# ✅ زيادة مهلة الطلبات (لعمليات التحديث الطويلة)
# ✅ ملحوظة: في Railway، المهلة الافتراضية 60 ثانية
# ✅ الحل الأفضل هو تشغيل التحديث في الخلفية (Background Task)

# ✅ إعدادات Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
    },
}
# ✅ إنشاء مجلد logs إذا لم يكن موجوداً
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'project/static')
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================================
# Google Sheets
# ==========================================================
GOOGLE_SERVICE_ACCOUNT_FILE = (
    BASE_DIR / "credentials" / "google-drive.json"
)
GOOGLE_SPREADSHEET_ID = (
    "1Qab6Psd4yqPJ9SUlz4F4y_6pD510p3A9sM-mXIr90wM"
)
TEMP_DIR = BASE_DIR / "temp"
TEMP_EXCEL_FILE = TEMP_DIR / "APP.xlsx"