# Generated by Django 5.2.15 on 2026-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatisticSheet15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الرقم الطبي')),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الرقم الحسابى')),
                ('patient_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المريض')),
                ('admission_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الدخول')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('month', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='الشهر')),
                ('specialty', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='التخصص')),
                ('package_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='اسم الباكدج')),
                ('entity_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الجهه')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='القطاع')),
                ('payment_type', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='نوع الدفع')),
                ('sub_company', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الشركه الفرعيه')),
                ('service_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='سعر الخدمه')),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='قيمة الفاتوره')),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الكود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقرير وإحصائية - شيت 15',
                'verbose_name_plural': 'التقارير والإحصائيات - شيت 15',
                'ordering': ['-admission_date', '-id'],
                'indexes': [models.Index(fields=['patient_name'], name='frontend_re_patient_aefe22_idx'), models.Index(fields=['entity_name'], name='frontend_re_entity__5406a8_idx'), models.Index(fields=['specialty'], name='frontend_re_special_e1717a_idx'), models.Index(fields=['package_name'], name='frontend_re_package_94b0b4_idx'), models.Index(fields=['admission_date'], name='frontend_re_admissi_1a6898_idx'), models.Index(fields=['sector'], name='frontend_re_sector_c434ef_idx'), models.Index(fields=['account_number'], name='frontend_re_account_f99f77_idx'), models.Index(fields=['month'], name='frontend_re_month_4d082c_idx'), models.Index(fields=['payment_type'], name='frontend_re_payment_934704_idx'), models.Index(fields=['code'], name='frontend_re_code_d2ef77_idx')],
            },
        ),
    ]
