# Generated by Django 5.2.15 on 2026-07-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatisticsheet15',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الطبيب'),
        ),
    ]
