# Generated by Django 5.2.15 on 2026-07-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_reportstatisticsheet15_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstatisticsheet15',
            name='invoice_value',
        ),
        migrations.AddField(
            model_name='reportstatisticsheet15',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='قيمة الفاتوره'),
        ),
        migrations.AddIndex(
            model_name='reportstatisticsheet15',
            index=models.Index(fields=['doctor_name'], name='frontend_re_doctor__896d29_idx'),
        ),
    ]
