# Generated by Django 5.2.15 on 2026-09-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_reportstatisticsheet15_invoice_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatisticsheet15',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='سعر الباكدج'),
        ),
    ]
